//! Generated protobuf modules with PGV validation.
//!
//! Validation rules are defined in proto files and auto-generated by prost-validate.
//! This crate isolates proto generation to speed up incremental builds.

// Implement proto extension traits for generated types
use auth_core::impl_proto_uuid;

// Re-export prost_types for use with google.protobuf.Struct and other well-known types
pub use prost_types;

#[allow(clippy::all, clippy::pedantic, dead_code)]
#[cfg_attr(doc, allow(unconditional_recursion))]
pub mod auth {
    tonic::include_proto!("auth");
}

#[allow(clippy::all, clippy::pedantic, dead_code)]
#[cfg_attr(doc, allow(unconditional_recursion))]
pub mod core {
    tonic::include_proto!("core");
}

// Register proto UUID types with the extension trait system
impl_proto_uuid!(core::Uuid);

/// Re-export file descriptor set for gRPC reflection.
#[cfg_attr(doc, allow(unconditional_recursion))]
pub const FILE_DESCRIPTOR_SET: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/file_descriptor_set.bin"));
