//! Generated protobuf modules with PGV validation and serde support.
//!
//! Validation rules are defined in proto files and auto-generated by prost-validate.
//! All messages derive `Serialize`/`Deserialize` following Google's protobuf JSON mapping.
//! This crate isolates proto generation to speed up incremental builds.

// Implement proto extension traits for generated types
use auth_core::impl_proto_uuid;

// Re-export prost_types for use with google.protobuf.Struct and other well-known types
pub use prost_types;

// Serde adapters for prost well-known types (Timestamp → RFC 3339, Duration → "Ns", FieldMask → "a,b")
pub mod serde_wkt;

#[allow(clippy::all, clippy::pedantic, dead_code)]
#[cfg_attr(doc, allow(unconditional_recursion))]
pub mod auth {
    pub mod v1 {
        tonic::include_proto!("auth.v1");
    }
    pub use v1::*;
}

#[allow(clippy::all, clippy::pedantic, dead_code)]
#[cfg_attr(doc, allow(unconditional_recursion))]
pub mod users {
    pub mod v1 {
        tonic::include_proto!("users.v1");
    }
    pub use v1::*;
}

#[allow(clippy::all, clippy::pedantic, dead_code)]
#[cfg_attr(doc, allow(unconditional_recursion))]
pub mod core {
    pub mod v1 {
        tonic::include_proto!("core.v1");
    }
    pub use v1::*;
}

/// REST-only message types (`HealthResponse`, `CheckResult`, etc.).
///
/// `OperationsService` gRPC trait is generated but intentionally unimplemented —
/// the service exists in proto solely to produce OpenAPI paths via gnostic.
/// Rust handlers in `src/routes.rs` use the message types directly.
#[allow(clippy::all, clippy::pedantic, dead_code)]
#[cfg_attr(doc, allow(unconditional_recursion))]
pub mod operations {
    pub mod v1 {
        tonic::include_proto!("operations.v1");
    }
    pub use v1::*;
}

// Register proto UUID types with the extension trait system
impl_proto_uuid!(core::Uuid);

/// Re-export file descriptor set for gRPC reflection.
#[cfg_attr(doc, allow(unconditional_recursion))]
pub const FILE_DESCRIPTOR_SET: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/file_descriptor_set.bin"));
