// Generated protobuf modules with PGV validation
// Validation rules are defined in proto files and auto-generated by prost-validate

#[allow(clippy::all)]
pub mod auth {
    tonic::include_proto!("auth");
}

#[allow(clippy::all)]
pub mod core {
    tonic::include_proto!("core");
}
